### ISSUE TITLE
Misleading information

### ISSUE THREAD

**Issue by CanadaHonk** [OfficiallySp/FeatherCord#4]
Readme is misleading, it shows 3 processes in use in task manager when it's using more as background processes, Electron cannot use that amount of ram whilst running normally.

**Comment by OfficiallySp** [comment]
the picture in the readme is over 2 years old. posting an updated one soon.

**Comment by Cregrant** [comment]
Fresh pics (only me in voice channel, muted microphone):
![17-11-2023 170132](https://github.com/OfficiallySp/FeatherCord/assets/62436046/5857f41a-43d4-44cf-b7e2-b0536d1daedf)
![17-11-2023 170350](https://github.com/OfficiallySp/FeatherCord/assets/62436046/fbc8159f-b2d2-46ba-b880-23e17e52e2c7)
