### ISSUE TITLE
Nativefier license violation

### ISSUE THREAD

**Issue by CanadaHonk** [OfficiallySp/FeatherCord#5]
There is no notice of using Nativefier, there disclosure and license should be included as per [the license](https://github.com/nativefier/nativefier/blob/master/LICENSE.md).

**Comment by OfficiallySp** [comment]
at any time. pressing Alt opens up a dropdown menu. under the help shows the app is built this way

**Comment by CanadaHonk** [comment]
You're still violating the license.
